package com.muddakir.quran;
import android.Manifest; import android.app.*; import android.content.*; import android.content.pm.PackageManager; import android.os.Build; import java.util.Calendar;
/** A lightweight local daily reminder. Friday opens the occasions page, other days open today's program. */
public final class DailyContentReminderWorker {
  private static final String PREFS="daily_content_reminder", CHANNEL="daily_content", ACTION="com.muddakir.quran.DAILY_CONTENT";
  private DailyContentReminderWorker(){}
  public static void ensureScheduled(Context c){
    SharedPreferences p=c.getSharedPreferences(PREFS,0); if(!p.getBoolean("enabled",true)) return; schedule(c);
  }
  public static void setEnabled(Context c,boolean enabled){c.getSharedPreferences(PREFS,0).edit().putBoolean("enabled",enabled).apply(); if(enabled)schedule(c);else cancel(c);}
  public static boolean isEnabled(Context c){return c.getSharedPreferences(PREFS,0).getBoolean("enabled",true);}
  private static void schedule(Context c){ AlarmManager am=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE); if(am==null)return; Calendar x=Calendar.getInstance();x.set(Calendar.HOUR_OF_DAY,9);x.set(Calendar.MINUTE,0);x.set(Calendar.SECOND,0);x.set(Calendar.MILLISECOND,0);if(x.getTimeInMillis()<=System.currentTimeMillis())x.add(Calendar.DAY_OF_YEAR,1); PendingIntent pi=pending(c); if(Build.VERSION.SDK_INT>=31&&!am.canScheduleExactAlarms())am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,x.getTimeInMillis(),pi);else if(Build.VERSION.SDK_INT>=23)am.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,x.getTimeInMillis(),pi);else am.setExact(AlarmManager.RTC_WAKEUP,x.getTimeInMillis(),pi); }
  private static void cancel(Context c){AlarmManager am=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE);if(am!=null)am.cancel(pending(c));}
  private static PendingIntent pending(Context c){Intent i=new Intent(c,DailyContentReminderReceiver.class).setAction(ACTION);return PendingIntent.getBroadcast(c,9201,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);}
  public static void show(Context c){ if(!c.getSharedPreferences("native_settings",Context.MODE_PRIVATE).getBoolean("notifications",true))return; if(!isEnabled(c))return; if(Build.VERSION.SDK_INT>=33&&c.checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)return; channel(c); Calendar now=Calendar.getInstance(); boolean friday=now.get(Calendar.DAY_OF_WEEK)==Calendar.FRIDAY; String title=friday?"🌙 يوم الجمعة المبارك":"🌿 برنامجك اليومي"; String text=friday?"اطّلع على أعمال الجمعة والمحتوى المناسب لهذا اليوم.":"وردك اليومي بانتظارك: قرآن، ذكر، ودعاء بخطوات بسيطة."; String page=friday?NativeNavigation.SCREEN_OCCASIONS:NativeNavigation.SCREEN_HOME; Intent open=new Intent(c,MainActivity.class).putExtra(MainActivity.EXTRA_OPEN_PAGE,page).setFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP); PendingIntent pi=PendingIntent.getActivity(c,9202,open,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE); Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(c,CHANNEL):new Notification.Builder(c);b.setSmallIcon(android.R.drawable.ic_popup_reminder).setContentTitle(title).setContentText(text).setStyle(new Notification.BigTextStyle().bigText(text)).setAutoCancel(true).setContentIntent(pi).setPriority(Notification.PRIORITY_DEFAULT);NotificationManager nm=(NotificationManager)c.getSystemService(Context.NOTIFICATION_SERVICE);if(nm!=null)nm.notify(9202,b.build()); }
  private static void channel(Context c){if(Build.VERSION.SDK_INT<26)return;NotificationManager nm=(NotificationManager)c.getSystemService(Context.NOTIFICATION_SERVICE);if(nm!=null)nm.createNotificationChannel(new NotificationChannel(CHANNEL,"برنامج اليوم",NotificationManager.IMPORTANCE_DEFAULT));}
}
