package com.muddakir.quran;
import android.*;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.os.Build;import java.util.*;
/** User-configurable reminders for Quran, du'a, daily program and occasions. */
public final class GeneralReminderWorker{
 public static final String PREFS="general_reminders", QURAN="quran", DUA="dua", PROGRAM="program", OCCASION="occasion"; private static final String CH="general_reminders";
 private GeneralReminderWorker(){}
 private static boolean valid(String t){return QURAN.equals(t)||DUA.equals(t)||PROGRAM.equals(t)||OCCASION.equals(t);}
 public static void set(Context c,String t,boolean on,int h,int m){if(!valid(t))return; h=Math.max(0,Math.min(23,h));m=Math.max(0,Math.min(59,m));c.getSharedPreferences(PREFS,0).edit().putBoolean("on_"+t,on).putInt("h_"+t,h).putInt("m_"+t,m).apply();if(on)schedule(c,t,h,m);else cancel(c,t);}
 public static boolean isEnabled(Context c,String t){return valid(t)&&c.getSharedPreferences(PREFS,0).getBoolean("on_"+t,false);} public static String time(Context c,String t){SharedPreferences p=c.getSharedPreferences(PREFS,0);int h=Math.max(0,Math.min(23,p.getInt("h_"+t,defH(t))));int m=Math.max(0,Math.min(59,p.getInt("m_"+t,0)));return String.format(Locale.US,"%02d:%02d",h,m);}
 public static void ensureScheduled(Context c){for(String t:new String[]{QURAN,DUA,PROGRAM,OCCASION}){if(isEnabled(c,t)){String[] a=time(c,t).split(":");schedule(c,t,Integer.parseInt(a[0]),Integer.parseInt(a[1]));}else cancel(c,t);}}
 private static void schedule(Context c,String t,int h,int m){AlarmManager am=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE);if(am==null)return;Calendar x=Calendar.getInstance();x.set(Calendar.HOUR_OF_DAY,h);x.set(Calendar.MINUTE,m);x.set(Calendar.SECOND,0);x.set(Calendar.MILLISECOND,0);if(x.getTimeInMillis()<=System.currentTimeMillis())x.add(Calendar.DAY_OF_YEAR,1);PendingIntent pi=pi(c,t);if(Build.VERSION.SDK_INT>=31&&!am.canScheduleExactAlarms())am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,x.getTimeInMillis(),pi);else if(Build.VERSION.SDK_INT>=23)am.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,x.getTimeInMillis(),pi);else am.setExact(AlarmManager.RTC_WAKEUP,x.getTimeInMillis(),pi);}
 private static void cancel(Context c,String t){AlarmManager am=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE);if(am!=null)am.cancel(pi(c,t));}
 private static PendingIntent pi(Context c,String t){Intent i=new Intent(c,GeneralReminderReceiver.class).setAction("com.muddakir.quran.GENERAL."+t).putExtra("type",t);return PendingIntent.getBroadcast(c,9300+id(t),i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);}
 public static void show(Context c,String t){if(!c.getSharedPreferences("native_settings",Context.MODE_PRIVATE).getBoolean("notifications",true))return;if(!isEnabled(c,t)||!valid(t))return;if(Build.VERSION.SDK_INT>=33&&c.checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=PackageManager.PERMISSION_GRANTED)return;String chId=channel(c);String page=QURAN.equals(t)?NativeNavigation.SCREEN_MUSHAF:DUA.equals(t)?NativeNavigation.SCREEN_ADHKAR:OCCASION.equals(t)?NativeNavigation.SCREEN_OCCASIONS:NativeNavigation.SCREEN_HOME;String title=QURAN.equals(t)?"📖 ورد القرآن":DUA.equals(t)?"🤲 وقت الدعاء":OCCASION.equals(t)?"📅 مناسبة اليوم":"🌿 برنامجك اليومي";String text=QURAN.equals(t)?"وردك القرآني بانتظارك. تابع من حيث توقفت.":DUA.equals(t)?"خصّص دقائق للدعاء وذكر الله.":OCCASION.equals(t)?"اطّلع على مناسبة اليوم والأعمال المرتبطة بها.":"أكمل خطوات برنامجك اليومي بهدوء.";Intent o=new Intent(c,MainActivity.class).putExtra(MainActivity.EXTRA_OPEN_PAGE,page).setFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP);PendingIntent p=PendingIntent.getActivity(c,9400+id(t),o,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(c,chId):new Notification.Builder(c);b.setSmallIcon(android.R.drawable.ic_popup_reminder).setContentTitle(title).setContentText(text).setStyle(new Notification.BigTextStyle().bigText(text)).setAutoCancel(true).setContentIntent(p).setPriority(Notification.PRIORITY_DEFAULT);NotificationManager nm=(NotificationManager)c.getSystemService(Context.NOTIFICATION_SERVICE);if(nm!=null)nm.notify(9400+id(t),b.build());}
 private static String channel(Context c){String chId=ReminderSoundStore.INSTANCE.channelId(c,CH);if(Build.VERSION.SDK_INT<26)return chId;NotificationManager nm=(NotificationManager)c.getSystemService(Context.NOTIFICATION_SERVICE);if(nm==null)return chId;if(nm.getNotificationChannel(chId)!=null)return chId;String prevId=ReminderSoundStore.INSTANCE.previousChannelId(c,CH);if(prevId!=null)nm.deleteNotificationChannel(prevId);NotificationChannel ch=new NotificationChannel(chId,"تذكيرات التطبيق",NotificationManager.IMPORTANCE_DEFAULT);android.net.Uri sound=ReminderSoundStore.INSTANCE.currentSoundUri(c);if(sound!=null)ch.setSound(sound,ReminderSoundStore.INSTANCE.notificationAudioAttributes());nm.createNotificationChannel(ch);return chId;}
 private static int id(String t){return QURAN.equals(t)?1:DUA.equals(t)?2:PROGRAM.equals(t)?3:4;} private static int defH(String t){return QURAN.equals(t)?8:DUA.equals(t)?20:PROGRAM.equals(t)?9:10;}
}
